name: Build and Deploy to github pages

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3.0.0

      - name: Install and Build 🔧
        uses: ossf/scorecard-action@main
        with:
          results_file: results.json
          results_format: json
          publish_results: true

